# ---------- Build stage ----------
FROM node:20-alpine AS build

WORKDIR /client

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build



FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /client/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
